Nation.create(name: 'Afghanistan', alpha_2_code: 'AF', alpha_3_code: 'AFG', numeric_code: '004', is_to_ship: true)
Nation.create(name: 'Åland Islands', alpha_2_code: 'AX', alpha_3_code: 'ALA', numeric_code: '248', is_to_ship: true)
Nation.create(name: 'Albania', alpha_2_code: 'AL', alpha_3_code: 'ALB', numeric_code: '008', is_to_ship: true)
Nation.create(name: 'Algeria', alpha_2_code: 'DZ', alpha_3_code: 'DZA', numeric_code: '012', is_to_ship: true)
Nation.create(name: 'American Samoa', alpha_2_code: 'AS', alpha_3_code: 'ASM', numeric_code: '016', is_to_ship: true)
Nation.create(name: 'Andorra', alpha_2_code: 'AD', alpha_3_code: 'AND', numeric_code: '020', is_to_ship: true)
Nation.create(name: 'Angola', alpha_2_code: 'AO', alpha_3_code: 'AGO', numeric_code: '024', is_to_ship: true)
Nation.create(name: 'Anguilla', alpha_2_code: 'AI', alpha_3_code: 'AIA', numeric_code: '660', is_to_ship: true)
Nation.create(name: 'Antarctica', alpha_2_code: 'AQ', alpha_3_code: 'ATA', numeric_code: '010', is_to_ship: true)
Nation.create(name: 'Antigua and Barbuda', alpha_2_code: 'AG', alpha_3_code: 'ATG', numeric_code: '028', is_to_ship: true)
Nation.create(name: 'Argentina', alpha_2_code: 'AR', alpha_3_code: 'ARG', numeric_code: '032', is_to_ship: true)
Nation.create(name: 'Armenia', alpha_2_code: 'AM', alpha_3_code: 'ARM', numeric_code: '051', is_to_ship: true)
Nation.create(name: 'Aruba', alpha_2_code: 'AW', alpha_3_code: 'ABW', numeric_code: '533', is_to_ship: true)
Nation.create(name: 'Australia', alpha_2_code: 'AU', alpha_3_code: 'AUS', numeric_code: '036', is_to_ship: true)
Nation.create(name: 'Austria', alpha_2_code: 'AT', alpha_3_code: 'AUT', numeric_code: '040', is_to_ship: true)
Nation.create(name: 'Azerbaijan', alpha_2_code: 'AZ', alpha_3_code: 'AZE', numeric_code: '031', is_to_ship: true)
Nation.create(name: 'Bahamas', alpha_2_code: 'BS', alpha_3_code: 'BHS', numeric_code: '044', is_to_ship: true)
Nation.create(name: 'Bahrain', alpha_2_code: 'BH', alpha_3_code: 'BHR', numeric_code: '048', is_to_ship: true)
Nation.create(name: 'Bangladesh', alpha_2_code: 'BD', alpha_3_code: 'BGD', numeric_code: '050', is_to_ship: true)
Nation.create(name: 'Barbados', alpha_2_code: 'BB', alpha_3_code: 'BRB', numeric_code: '052', is_to_ship: true)
Nation.create(name: 'Belarus', alpha_2_code: 'BY', alpha_3_code: 'BLR', numeric_code: '112', is_to_ship: true)
Nation.create(name: 'Belgium', alpha_2_code: 'BE', alpha_3_code: 'BEL', numeric_code: '056', is_to_ship: true)
Nation.create(name: 'Belize', alpha_2_code: 'BZ', alpha_3_code: 'BLZ', numeric_code: '084', is_to_ship: true)
Nation.create(name: 'Benin', alpha_2_code: 'BJ', alpha_3_code: 'BEN', numeric_code: '204', is_to_ship: true)
Nation.create(name: 'Bermuda', alpha_2_code: 'BM', alpha_3_code: 'BMU', numeric_code: '060', is_to_ship: true)
Nation.create(name: 'Bhutan', alpha_2_code: 'BT', alpha_3_code: 'BTN', numeric_code: '064', is_to_ship: true)
Nation.create(name: 'Bolivia (Plurinational State of)', alpha_2_code: 'BO', alpha_3_code: 'BOL', numeric_code: '068', is_to_ship: true)
Nation.create(name: 'Bonaire, Sint Eustatius and Saba', alpha_2_code: 'BQ', alpha_3_code: 'BES', numeric_code: '535', is_to_ship: true)
Nation.create(name: 'Bosnia and Herzegovina', alpha_2_code: 'BA', alpha_3_code: 'BIH', numeric_code: '070', is_to_ship: true)
Nation.create(name: 'Botswana', alpha_2_code: 'BW', alpha_3_code: 'BWA', numeric_code: '072', is_to_ship: true)
Nation.create(name: 'Bouvet Island', alpha_2_code: 'BV', alpha_3_code: 'BVT', numeric_code: '074', is_to_ship: true)
Nation.create(name: 'Brazil', alpha_2_code: 'BR', alpha_3_code: 'BRA', numeric_code: '076', is_to_ship: true)
Nation.create(name: 'British Indian Ocean Territory', alpha_2_code: 'IO', alpha_3_code: 'IOT', numeric_code: '086', is_to_ship: true)
Nation.create(name: 'Brunei Darussalam', alpha_2_code: 'BN', alpha_3_code: 'BRN', numeric_code: '096', is_to_ship: true)
Nation.create(name: 'Bulgaria', alpha_2_code: 'BG', alpha_3_code: 'BGR', numeric_code: '100', is_to_ship: true)
Nation.create(name: 'Burkina Faso', alpha_2_code: 'BF', alpha_3_code: 'BFA', numeric_code: '854', is_to_ship: true)
Nation.create(name: 'Burundi', alpha_2_code: 'BI', alpha_3_code: 'BDI', numeric_code: '108', is_to_ship: true)
Nation.create(name: 'Cabo Verde', alpha_2_code: 'CV', alpha_3_code: 'CPV', numeric_code: '132', is_to_ship: true)
Nation.create(name: 'Cambodia', alpha_2_code: 'KH', alpha_3_code: 'KHM', numeric_code: '116', is_to_ship: true)
Nation.create(name: 'Cameroon', alpha_2_code: 'CM', alpha_3_code: 'CMR', numeric_code: '120', is_to_ship: true)
Nation.create(name: 'Canada', alpha_2_code: 'CA', alpha_3_code: 'CAN', numeric_code: '124', is_to_ship: true)
Nation.create(name: 'Cayman Islands', alpha_2_code: 'KY', alpha_3_code: 'CYM', numeric_code: '136', is_to_ship: true)
Nation.create(name: 'Central African Republic', alpha_2_code: 'CF', alpha_3_code: 'CAF', numeric_code: '140', is_to_ship: true)
Nation.create(name: 'Chad', alpha_2_code: 'TD', alpha_3_code: 'TCD', numeric_code: '148', is_to_ship: true)
Nation.create(name: 'Chile', alpha_2_code: 'CL', alpha_3_code: 'CHL', numeric_code: '152', is_to_ship: true)
Nation.create(name: 'China', alpha_2_code: 'CN', alpha_3_code: 'CHN', numeric_code: '156', is_to_ship: true)
Nation.create(name: 'Christmas Island', alpha_2_code: 'CX', alpha_3_code: 'CXR', numeric_code: '162', is_to_ship: true)
Nation.create(name: 'Cocos (Keeling) Islands', alpha_2_code: 'CC', alpha_3_code: 'CCK', numeric_code: '166', is_to_ship: true)
Nation.create(name: 'Colombia', alpha_2_code: 'CO', alpha_3_code: 'COL', numeric_code: '170', is_to_ship: true)
Nation.create(name: 'Comoros', alpha_2_code: 'KM', alpha_3_code: 'COM', numeric_code: '174', is_to_ship: true)
Nation.create(name: 'Congo', alpha_2_code: 'CG', alpha_3_code: 'COG', numeric_code: '178', is_to_ship: true)
Nation.create(name: 'Congo (Democratic Republic of the)', alpha_2_code: 'CD', alpha_3_code: 'COD', numeric_code: '180', is_to_ship: true)
Nation.create(name: 'Cook Islands', alpha_2_code: 'CK', alpha_3_code: 'COK', numeric_code: '184', is_to_ship: true)
Nation.create(name: 'Costa Rica', alpha_2_code: 'CR', alpha_3_code: 'CRI', numeric_code: '188', is_to_ship: true)
Nation.create(name: 'Côte d\'Ivoire', alpha_2_code: 'CI', alpha_3_code: 'CIV', numeric_code: '384', is_to_ship: true)
Nation.create(name: 'Croatia', alpha_2_code: 'HR', alpha_3_code: 'HRV', numeric_code: '191', is_to_ship: true)
Nation.create(name: 'Cuba', alpha_2_code: 'CU', alpha_3_code: 'CUB', numeric_code: '192', is_to_ship: true)
Nation.create(name: 'Curaçao', alpha_2_code: 'CW', alpha_3_code: 'CUW', numeric_code: '531', is_to_ship: true)
Nation.create(name: 'Cyprus', alpha_2_code: 'CY', alpha_3_code: 'CYP', numeric_code: '196', is_to_ship: true)
Nation.create(name: 'Czech Republic', alpha_2_code: 'CZ', alpha_3_code: 'CZE', numeric_code: '203', is_to_ship: true)
Nation.create(name: 'Denmark', alpha_2_code: 'DK', alpha_3_code: 'DNK', numeric_code: '208', is_to_ship: true)
Nation.create(name: 'Djibouti', alpha_2_code: 'DJ', alpha_3_code: 'DJI', numeric_code: '262', is_to_ship: true)
Nation.create(name: 'Dominica', alpha_2_code: 'DM', alpha_3_code: 'DMA', numeric_code: '212', is_to_ship: true)
Nation.create(name: 'Dominican Republic', alpha_2_code: 'DO', alpha_3_code: 'DOM', numeric_code: '214', is_to_ship: true)
Nation.create(name: 'Ecuador', alpha_2_code: 'EC', alpha_3_code: 'ECU', numeric_code: '218', is_to_ship: true)
Nation.create(name: 'Egypt', alpha_2_code: 'EG', alpha_3_code: 'EGY', numeric_code: '818', is_to_ship: true)
Nation.create(name: 'El Salvador', alpha_2_code: 'SV', alpha_3_code: 'SLV', numeric_code: '222', is_to_ship: true)
Nation.create(name: 'Equatorial Guinea', alpha_2_code: 'GQ', alpha_3_code: 'GNQ', numeric_code: '226', is_to_ship: true)
Nation.create(name: 'Eritrea', alpha_2_code: 'ER', alpha_3_code: 'ERI', numeric_code: '232', is_to_ship: true)
Nation.create(name: 'Estonia', alpha_2_code: 'EE', alpha_3_code: 'EST', numeric_code: '233', is_to_ship: true)
Nation.create(name: 'Ethiopia', alpha_2_code: 'ET', alpha_3_code: 'ETH', numeric_code: '231', is_to_ship: true)
Nation.create(name: 'Falkland Islands (Malvinas)', alpha_2_code: 'FK', alpha_3_code: 'FLK', numeric_code: '238', is_to_ship: true)
Nation.create(name: 'Faroe Islands', alpha_2_code: 'FO', alpha_3_code: 'FRO', numeric_code: '234', is_to_ship: true)
Nation.create(name: 'Fiji', alpha_2_code: 'FJ', alpha_3_code: 'FJI', numeric_code: '242', is_to_ship: true)
Nation.create(name: 'Finland', alpha_2_code: 'FI', alpha_3_code: 'FIN', numeric_code: '246', is_to_ship: true)
Nation.create(name: 'France', alpha_2_code: 'FR', alpha_3_code: 'FRA', numeric_code: '250', is_to_ship: true)
Nation.create(name: 'French Guiana', alpha_2_code: 'GF', alpha_3_code: 'GUF', numeric_code: '254', is_to_ship: true)
Nation.create(name: 'French Polynesia', alpha_2_code: 'PF', alpha_3_code: 'PYF', numeric_code: '258', is_to_ship: true)
Nation.create(name: 'French Southern Territories', alpha_2_code: 'TF', alpha_3_code: 'ATF', numeric_code: '260', is_to_ship: true)
Nation.create(name: 'Gabon', alpha_2_code: 'GA', alpha_3_code: 'GAB', numeric_code: '266', is_to_ship: true)
Nation.create(name: 'Gambia', alpha_2_code: 'GM', alpha_3_code: 'GMB', numeric_code: '270', is_to_ship: true)
Nation.create(name: 'Georgia', alpha_2_code: 'GE', alpha_3_code: 'GEO', numeric_code: '268', is_to_ship: true)
Nation.create(name: 'Germany', alpha_2_code: 'DE', alpha_3_code: 'DEU', numeric_code: '276', is_to_ship: true)
Nation.create(name: 'Ghana', alpha_2_code: 'GH', alpha_3_code: 'GHA', numeric_code: '288', is_to_ship: true)
Nation.create(name: 'Gibraltar', alpha_2_code: 'GI', alpha_3_code: 'GIB', numeric_code: '292', is_to_ship: true)
Nation.create(name: 'Greece', alpha_2_code: 'GR', alpha_3_code: 'GRC', numeric_code: '300', is_to_ship: true)
Nation.create(name: 'Greenland', alpha_2_code: 'GL', alpha_3_code: 'GRL', numeric_code: '304', is_to_ship: true)
Nation.create(name: 'Grenada', alpha_2_code: 'GD', alpha_3_code: 'GRD', numeric_code: '308', is_to_ship: true)
Nation.create(name: 'Guadeloupe', alpha_2_code: 'GP', alpha_3_code: 'GLP', numeric_code: '312', is_to_ship: true)
Nation.create(name: 'Guam', alpha_2_code: 'GU', alpha_3_code: 'GUM', numeric_code: '316', is_to_ship: true)
Nation.create(name: 'Guatemala', alpha_2_code: 'GT', alpha_3_code: 'GTM', numeric_code: '320', is_to_ship: true)
Nation.create(name: 'Guernsey', alpha_2_code: 'GG', alpha_3_code: 'GGY', numeric_code: '831', is_to_ship: true)
Nation.create(name: 'Guinea', alpha_2_code: 'GN', alpha_3_code: 'GIN', numeric_code: '324', is_to_ship: true)
Nation.create(name: 'Guinea-Bissau', alpha_2_code: 'GW', alpha_3_code: 'GNB', numeric_code: '624', is_to_ship: true)
Nation.create(name: 'Guyana', alpha_2_code: 'GY', alpha_3_code: 'GUY', numeric_code: '328', is_to_ship: true)
Nation.create(name: 'Haiti', alpha_2_code: 'HT', alpha_3_code: 'HTI', numeric_code: '332', is_to_ship: true)
Nation.create(name: 'Heard Island and McDonald Islands', alpha_2_code: 'HM', alpha_3_code: 'HMD', numeric_code: '334', is_to_ship: true)
Nation.create(name: 'Holy See', alpha_2_code: 'VA', alpha_3_code: 'VAT', numeric_code: '336', is_to_ship: true)
Nation.create(name: 'Honduras', alpha_2_code: 'HN', alpha_3_code: 'HND', numeric_code: '340', is_to_ship: true)
Nation.create(name: 'Hong Kong', alpha_2_code: 'HK', alpha_3_code: 'HKG', numeric_code: '344', is_to_ship: true)
Nation.create(name: 'Hungary', alpha_2_code: 'HU', alpha_3_code: 'HUN', numeric_code: '348', is_to_ship: true)
Nation.create(name: 'Iceland', alpha_2_code: 'IS', alpha_3_code: 'ISL', numeric_code: '352', is_to_ship: true)
Nation.create(name: 'India', alpha_2_code: 'IN', alpha_3_code: 'IND', numeric_code: '356', is_to_ship: true)
Nation.create(name: 'Indonesia', alpha_2_code: 'ID', alpha_3_code: 'IDN', numeric_code: '360', is_to_ship: true)
Nation.create(name: 'Iran (Islamic Republic of)', alpha_2_code: 'IR', alpha_3_code: 'IRN', numeric_code: '364', is_to_ship: true)
Nation.create(name: 'Iraq', alpha_2_code: 'IQ', alpha_3_code: 'IRQ', numeric_code: '368', is_to_ship: true)
Nation.create(name: 'Ireland', alpha_2_code: 'IE', alpha_3_code: 'IRL', numeric_code: '372', is_to_ship: true)
Nation.create(name: 'Isle of Man', alpha_2_code: 'IM', alpha_3_code: 'IMN', numeric_code: '833', is_to_ship: true)
Nation.create(name: 'Israel', alpha_2_code: 'IL', alpha_3_code: 'ISR', numeric_code: '376', is_to_ship: true)
Nation.create(name: 'Italy', alpha_2_code: 'IT', alpha_3_code: 'ITA', numeric_code: '380', is_to_ship: true)
Nation.create(name: 'Jamaica', alpha_2_code: 'JM', alpha_3_code: 'JAM', numeric_code: '388', is_to_ship: true)
Nation.create(name: 'Japan', alpha_2_code: 'JP', alpha_3_code: 'JPN', numeric_code: '392', is_to_ship: true)
Nation.create(name: 'Jersey', alpha_2_code: 'JE', alpha_3_code: 'JEY', numeric_code: '832', is_to_ship: true)
Nation.create(name: 'Jordan', alpha_2_code: 'JO', alpha_3_code: 'JOR', numeric_code: '400', is_to_ship: true)
Nation.create(name: 'Kazakhstan', alpha_2_code: 'KZ', alpha_3_code: 'KAZ', numeric_code: '398', is_to_ship: true)
Nation.create(name: 'Kenya', alpha_2_code: 'KE', alpha_3_code: 'KEN', numeric_code: '404', is_to_ship: true)
Nation.create(name: 'Kiribati', alpha_2_code: 'KI', alpha_3_code: 'KIR', numeric_code: '296', is_to_ship: true)
Nation.create(name: 'North Korea', alpha_2_code: 'KP', alpha_3_code: 'PRK', numeric_code: '408', is_to_ship: false)
Nation.create(name: 'South Korea', alpha_2_code: 'KR', alpha_3_code: 'KOR', numeric_code: '410', is_to_ship: true)
Nation.create(name: 'Kuwait', alpha_2_code: 'KW', alpha_3_code: 'KWT', numeric_code: '414', is_to_ship: true)
Nation.create(name: 'Kyrgyzstan', alpha_2_code: 'KG', alpha_3_code: 'KGZ', numeric_code: '417', is_to_ship: true)
Nation.create(name: 'Lao People\'s Democratic Republic', alpha_2_code: 'LA', alpha_3_code: 'LAO', numeric_code: '418', is_to_ship: true)
Nation.create(name: 'Latvia', alpha_2_code: 'LV', alpha_3_code: 'LVA', numeric_code: '428', is_to_ship: true)
Nation.create(name: 'Lebanon', alpha_2_code: 'LB', alpha_3_code: 'LBN', numeric_code: '422', is_to_ship: true)
Nation.create(name: 'Lesotho', alpha_2_code: 'LS', alpha_3_code: 'LSO', numeric_code: '426', is_to_ship: true)
Nation.create(name: 'Liberia', alpha_2_code: 'LR', alpha_3_code: 'LBR', numeric_code: '430', is_to_ship: true)
Nation.create(name: 'Libya', alpha_2_code: 'LY', alpha_3_code: 'LBY', numeric_code: '434', is_to_ship: true)
Nation.create(name: 'Liechtenstein', alpha_2_code: 'LI', alpha_3_code: 'LIE', numeric_code: '438', is_to_ship: true)
Nation.create(name: 'Lithuania', alpha_2_code: 'LT', alpha_3_code: 'LTU', numeric_code: '440', is_to_ship: true)
Nation.create(name: 'Luxembourg', alpha_2_code: 'LU', alpha_3_code: 'LUX', numeric_code: '442', is_to_ship: true)
Nation.create(name: 'Macao', alpha_2_code: 'MO', alpha_3_code: 'MAC', numeric_code: '446', is_to_ship: true)
Nation.create(name: 'Macedonia (the former Yugoslav Republic of)', alpha_2_code: 'MK', alpha_3_code: 'MKD', numeric_code: '807', is_to_ship: true)
Nation.create(name: 'Madagascar', alpha_2_code: 'MG', alpha_3_code: 'MDG', numeric_code: '450', is_to_ship: true)
Nation.create(name: 'Malawi', alpha_2_code: 'MW', alpha_3_code: 'MWI', numeric_code: '454', is_to_ship: true)
Nation.create(name: 'Malaysia', alpha_2_code: 'MY', alpha_3_code: 'MYS', numeric_code: '458', is_to_ship: true)
Nation.create(name: 'Maldives', alpha_2_code: 'MV', alpha_3_code: 'MDV', numeric_code: '462', is_to_ship: true)
Nation.create(name: 'Mali', alpha_2_code: 'ML', alpha_3_code: 'MLI', numeric_code: '466', is_to_ship: true)
Nation.create(name: 'Malta', alpha_2_code: 'MT', alpha_3_code: 'MLT', numeric_code: '470', is_to_ship: true)
Nation.create(name: 'Marshall Islands', alpha_2_code: 'MH', alpha_3_code: 'MHL', numeric_code: '584', is_to_ship: true)
Nation.create(name: 'Martinique', alpha_2_code: 'MQ', alpha_3_code: 'MTQ', numeric_code: '474', is_to_ship: true)
Nation.create(name: 'Mauritania', alpha_2_code: 'MR', alpha_3_code: 'MRT', numeric_code: '478', is_to_ship: true)
Nation.create(name: 'Mauritius', alpha_2_code: 'MU', alpha_3_code: 'MUS', numeric_code: '480', is_to_ship: true)
Nation.create(name: 'Mayotte', alpha_2_code: 'YT', alpha_3_code: 'MYT', numeric_code: '175', is_to_ship: true)
Nation.create(name: 'Mexico', alpha_2_code: 'MX', alpha_3_code: 'MEX', numeric_code: '484', is_to_ship: true)
Nation.create(name: 'Micronesia (Federated States of)', alpha_2_code: 'FM', alpha_3_code: 'FSM', numeric_code: '583', is_to_ship: true)
Nation.create(name: 'Moldova (Republic of)', alpha_2_code: 'MD', alpha_3_code: 'MDA', numeric_code: '498', is_to_ship: true)
Nation.create(name: 'Monaco', alpha_2_code: 'MC', alpha_3_code: 'MCO', numeric_code: '492', is_to_ship: true)
Nation.create(name: 'Mongolia', alpha_2_code: 'MN', alpha_3_code: 'MNG', numeric_code: '496', is_to_ship: true)
Nation.create(name: 'Montenegro', alpha_2_code: 'ME', alpha_3_code: 'MNE', numeric_code: '499', is_to_ship: true)
Nation.create(name: 'Montserrat', alpha_2_code: 'MS', alpha_3_code: 'MSR', numeric_code: '500', is_to_ship: true)
Nation.create(name: 'Morocco', alpha_2_code: 'MA', alpha_3_code: 'MAR', numeric_code: '504', is_to_ship: true)
Nation.create(name: 'Mozambique', alpha_2_code: 'MZ', alpha_3_code: 'MOZ', numeric_code: '508', is_to_ship: true)
Nation.create(name: 'Myanmar', alpha_2_code: 'MM', alpha_3_code: 'MMR', numeric_code: '104', is_to_ship: true)
Nation.create(name: 'Namibia', alpha_2_code: 'NA', alpha_3_code: 'NAM', numeric_code: '516', is_to_ship: true)
Nation.create(name: 'Nauru', alpha_2_code: 'NR', alpha_3_code: 'NRU', numeric_code: '520', is_to_ship: true)
Nation.create(name: 'Nepal', alpha_2_code: 'NP', alpha_3_code: 'NPL', numeric_code: '524', is_to_ship: true)
Nation.create(name: 'Netherlands', alpha_2_code: 'NL', alpha_3_code: 'NLD', numeric_code: '528', is_to_ship: true)
Nation.create(name: 'New Caledonia', alpha_2_code: 'NC', alpha_3_code: 'NCL', numeric_code: '540', is_to_ship: true)
Nation.create(name: 'New Zealand', alpha_2_code: 'NZ', alpha_3_code: 'NZL', numeric_code: '554', is_to_ship: true)
Nation.create(name: 'Nicaragua', alpha_2_code: 'NI', alpha_3_code: 'NIC', numeric_code: '558', is_to_ship: true)
Nation.create(name: 'Niger', alpha_2_code: 'NE', alpha_3_code: 'NER', numeric_code: '562', is_to_ship: true)
Nation.create(name: 'Nigeria', alpha_2_code: 'NG', alpha_3_code: 'NGA', numeric_code: '566', is_to_ship: true)
Nation.create(name: 'Niue', alpha_2_code: 'NU', alpha_3_code: 'NIU', numeric_code: '570', is_to_ship: true)
Nation.create(name: 'Norfolk Island', alpha_2_code: 'NF', alpha_3_code: 'NFK', numeric_code: '574', is_to_ship: true)
Nation.create(name: 'Northern Mariana Islands', alpha_2_code: 'MP', alpha_3_code: 'MNP', numeric_code: '580', is_to_ship: true)
Nation.create(name: 'Norway', alpha_2_code: 'NO', alpha_3_code: 'NOR', numeric_code: '578', is_to_ship: true)
Nation.create(name: 'Oman', alpha_2_code: 'OM', alpha_3_code: 'OMN', numeric_code: '512', is_to_ship: true)
Nation.create(name: 'Pakistan', alpha_2_code: 'PK', alpha_3_code: 'PAK', numeric_code: '586', is_to_ship: true)
Nation.create(name: 'Palau', alpha_2_code: 'PW', alpha_3_code: 'PLW', numeric_code: '585', is_to_ship: true)
Nation.create(name: 'Palestine, State of', alpha_2_code: 'PS', alpha_3_code: 'PSE', numeric_code: '275', is_to_ship: true)
Nation.create(name: 'Panama', alpha_2_code: 'PA', alpha_3_code: 'PAN', numeric_code: '591', is_to_ship: true)
Nation.create(name: 'Papua New Guinea', alpha_2_code: 'PG', alpha_3_code: 'PNG', numeric_code: '598', is_to_ship: true)
Nation.create(name: 'Paraguay', alpha_2_code: 'PY', alpha_3_code: 'PRY', numeric_code: '600', is_to_ship: true)
Nation.create(name: 'Peru', alpha_2_code: 'PE', alpha_3_code: 'PER', numeric_code: '604', is_to_ship: true)
Nation.create(name: 'Philippines', alpha_2_code: 'PH', alpha_3_code: 'PHL', numeric_code: '608', is_to_ship: true)
Nation.create(name: 'Pitcairn', alpha_2_code: 'PN', alpha_3_code: 'PCN', numeric_code: '612', is_to_ship: true)
Nation.create(name: 'Poland', alpha_2_code: 'PL', alpha_3_code: 'POL', numeric_code: '616', is_to_ship: true)
Nation.create(name: 'Portugal', alpha_2_code: 'PT', alpha_3_code: 'PRT', numeric_code: '620', is_to_ship: true)
Nation.create(name: 'Puerto Rico', alpha_2_code: 'PR', alpha_3_code: 'PRI', numeric_code: '630', is_to_ship: true)
Nation.create(name: 'Qatar', alpha_2_code: 'QA', alpha_3_code: 'QAT', numeric_code: '634', is_to_ship: true)
Nation.create(name: 'Réunion', alpha_2_code: 'RE', alpha_3_code: 'REU', numeric_code: '638', is_to_ship: true)
Nation.create(name: 'Romania', alpha_2_code: 'RO', alpha_3_code: 'ROU', numeric_code: '642', is_to_ship: true)
Nation.create(name: 'Russian Federation', alpha_2_code: 'RU', alpha_3_code: 'RUS', numeric_code: '643', is_to_ship: true)
Nation.create(name: 'Rwanda', alpha_2_code: 'RW', alpha_3_code: 'RWA', numeric_code: '646', is_to_ship: true)
Nation.create(name: 'Saint Barthélemy', alpha_2_code: 'BL', alpha_3_code: 'BLM', numeric_code: '652', is_to_ship: true)
Nation.create(name: 'Saint Helena, Ascension and Tristan da Cunha', alpha_2_code: 'SH', alpha_3_code: 'SHN', numeric_code: '654', is_to_ship: true)
Nation.create(name: 'Saint Kitts and Nevis', alpha_2_code: 'KN', alpha_3_code: 'KNA', numeric_code: '659', is_to_ship: true)
Nation.create(name: 'Saint Lucia', alpha_2_code: 'LC', alpha_3_code: 'LCA', numeric_code: '662', is_to_ship: true)
Nation.create(name: 'Saint Martin (French part)', alpha_2_code: 'MF', alpha_3_code: 'MAF', numeric_code: '663', is_to_ship: true)
Nation.create(name: 'Saint Pierre and Miquelon', alpha_2_code: 'PM', alpha_3_code: 'SPM', numeric_code: '666', is_to_ship: true)
Nation.create(name: 'Saint Vincent and the Grenadines', alpha_2_code: 'VC', alpha_3_code: 'VCT', numeric_code: '670', is_to_ship: true)
Nation.create(name: 'Samoa', alpha_2_code: 'WS', alpha_3_code: 'WSM', numeric_code: '882', is_to_ship: true)
Nation.create(name: 'San Marino', alpha_2_code: 'SM', alpha_3_code: 'SMR', numeric_code: '674', is_to_ship: true)
Nation.create(name: 'Sao Tome and Principe', alpha_2_code: 'ST', alpha_3_code: 'STP', numeric_code: '678', is_to_ship: true)
Nation.create(name: 'Saudi Arabia', alpha_2_code: 'SA', alpha_3_code: 'SAU', numeric_code: '682', is_to_ship: true)
Nation.create(name: 'Senegal', alpha_2_code: 'SN', alpha_3_code: 'SEN', numeric_code: '686', is_to_ship: true)
Nation.create(name: 'Serbia', alpha_2_code: 'RS', alpha_3_code: 'SRB', numeric_code: '688', is_to_ship: true)
Nation.create(name: 'Seychelles', alpha_2_code: 'SC', alpha_3_code: 'SYC', numeric_code: '690', is_to_ship: true)
Nation.create(name: 'Sierra Leone', alpha_2_code: 'SL', alpha_3_code: 'SLE', numeric_code: '694', is_to_ship: true)
Nation.create(name: 'Singapore', alpha_2_code: 'SG', alpha_3_code: 'SGP', numeric_code: '702', is_to_ship: true)
Nation.create(name: 'Sint Maarten (Dutch part)', alpha_2_code: 'SX', alpha_3_code: 'SXM', numeric_code: '534', is_to_ship: true)
Nation.create(name: 'Slovakia', alpha_2_code: 'SK', alpha_3_code: 'SVK', numeric_code: '703', is_to_ship: true)
Nation.create(name: 'Slovenia', alpha_2_code: 'SI', alpha_3_code: 'SVN', numeric_code: '705', is_to_ship: true)
Nation.create(name: 'Solomon Islands', alpha_2_code: 'SB', alpha_3_code: 'SLB', numeric_code: '090', is_to_ship: true)
Nation.create(name: 'Somalia', alpha_2_code: 'SO', alpha_3_code: 'SOM', numeric_code: '706', is_to_ship: true)
Nation.create(name: 'South Africa', alpha_2_code: 'ZA', alpha_3_code: 'ZAF', numeric_code: '710', is_to_ship: true)
Nation.create(name: 'South Georgia and the South Sandwich Islands', alpha_2_code: 'GS', alpha_3_code: 'SGS', numeric_code: '239', is_to_ship: true)
Nation.create(name: 'South Sudan', alpha_2_code: 'SS', alpha_3_code: 'SSD', numeric_code: '728', is_to_ship: true)
Nation.create(name: 'Spain', alpha_2_code: 'ES', alpha_3_code: 'ESP', numeric_code: '724', is_to_ship: true)
Nation.create(name: 'Sri Lanka', alpha_2_code: 'LK', alpha_3_code: 'LKA', numeric_code: '144', is_to_ship: true)
Nation.create(name: 'Sudan', alpha_2_code: 'SD', alpha_3_code: 'SDN', numeric_code: '729', is_to_ship: true)
Nation.create(name: 'Suriname', alpha_2_code: 'SR', alpha_3_code: 'SUR', numeric_code: '740', is_to_ship: true)
Nation.create(name: 'Svalbard and Jan Mayen', alpha_2_code: 'SJ', alpha_3_code: 'SJM', numeric_code: '744', is_to_ship: true)
Nation.create(name: 'Swaziland', alpha_2_code: 'SZ', alpha_3_code: 'SWZ', numeric_code: '748', is_to_ship: true)
Nation.create(name: 'Sweden', alpha_2_code: 'SE', alpha_3_code: 'SWE', numeric_code: '752', is_to_ship: true)
Nation.create(name: 'Switzerland', alpha_2_code: 'CH', alpha_3_code: 'CHE', numeric_code: '756', is_to_ship: true)
Nation.create(name: 'Syrian Arab Republic', alpha_2_code: 'SY', alpha_3_code: 'SYR', numeric_code: '760', is_to_ship: true)
Nation.create(name: 'Taiwan, Province of China[a]', alpha_2_code: 'TW', alpha_3_code: 'TWN', numeric_code: '158', is_to_ship: true)
Nation.create(name: 'Tajikistan', alpha_2_code: 'TJ', alpha_3_code: 'TJK', numeric_code: '762', is_to_ship: true)
Nation.create(name: 'Tanzania, United Republic of', alpha_2_code: 'TZ', alpha_3_code: 'TZA', numeric_code: '834', is_to_ship: true)
Nation.create(name: 'Thailand', alpha_2_code: 'TH', alpha_3_code: 'THA', numeric_code: '764', is_to_ship: true)
Nation.create(name: 'Timor-Leste', alpha_2_code: 'TL', alpha_3_code: 'TLS', numeric_code: '626', is_to_ship: true)
Nation.create(name: 'Togo', alpha_2_code: 'TG', alpha_3_code: 'TGO', numeric_code: '768', is_to_ship: true)
Nation.create(name: 'Tokelau', alpha_2_code: 'TK', alpha_3_code: 'TKL', numeric_code: '772', is_to_ship: true)
Nation.create(name: 'Tonga', alpha_2_code: 'TO', alpha_3_code: 'TON', numeric_code: '776', is_to_ship: true)
Nation.create(name: 'Trinidad and Tobago', alpha_2_code: 'TT', alpha_3_code: 'TTO', numeric_code: '780', is_to_ship: true)
Nation.create(name: 'Tunisia', alpha_2_code: 'TN', alpha_3_code: 'TUN', numeric_code: '788', is_to_ship: true)
Nation.create(name: 'Turkey', alpha_2_code: 'TR', alpha_3_code: 'TUR', numeric_code: '792', is_to_ship: true)
Nation.create(name: 'Turkmenistan', alpha_2_code: 'TM', alpha_3_code: 'TKM', numeric_code: '795', is_to_ship: true)
Nation.create(name: 'Turks and Caicos Islands', alpha_2_code: 'TC', alpha_3_code: 'TCA', numeric_code: '796', is_to_ship: true)
Nation.create(name: 'Tuvalu', alpha_2_code: 'TV', alpha_3_code: 'TUV', numeric_code: '798', is_to_ship: true)
Nation.create(name: 'Uganda', alpha_2_code: 'UG', alpha_3_code: 'UGA', numeric_code: '800', is_to_ship: true)
Nation.create(name: 'Ukraine', alpha_2_code: 'UA', alpha_3_code: 'UKR', numeric_code: '804', is_to_ship: true)
Nation.create(name: 'United Arab Emirates', alpha_2_code: 'AE', alpha_3_code: 'ARE', numeric_code: '784', is_to_ship: true)
Nation.create(name: 'United Kingdom of Great Britain and Northern Ireland', alpha_2_code: 'GB', alpha_3_code: 'GBR', numeric_code: '826', is_to_ship: true)
Nation.create(name: 'United States of America', alpha_2_code: 'US', alpha_3_code: 'USA', numeric_code: '840', is_to_ship: true)
Nation.create(name: 'United States Minor Outlying Islands', alpha_2_code: 'UM', alpha_3_code: 'UMI', numeric_code: '581', is_to_ship: true)
Nation.create(name: 'Uruguay', alpha_2_code: 'UY', alpha_3_code: 'URY', numeric_code: '858', is_to_ship: true)
Nation.create(name: 'Uzbekistan', alpha_2_code: 'UZ', alpha_3_code: 'UZB', numeric_code: '860', is_to_ship: true)
Nation.create(name: 'Vanuatu', alpha_2_code: 'VU', alpha_3_code: 'VUT', numeric_code: '548', is_to_ship: true)
Nation.create(name: 'Venezuela (Bolivarian Republic of)', alpha_2_code: 'VE', alpha_3_code: 'VEN', numeric_code: '862', is_to_ship: true)
Nation.create(name: 'Viet Nam', alpha_2_code: 'VN', alpha_3_code: 'VNM', numeric_code: '704', is_to_ship: true)
Nation.create(name: 'Virgin Islands (British)', alpha_2_code: 'VG', alpha_3_code: 'VGB', numeric_code: '092', is_to_ship: true)
Nation.create(name: 'Virgin Islands (U.S.)', alpha_2_code: 'VI', alpha_3_code: 'VIR', numeric_code: '850', is_to_ship: true)
Nation.create(name: 'Wallis and Futuna', alpha_2_code: 'WF', alpha_3_code: 'WLF', numeric_code: '876', is_to_ship: true)
Nation.create(name: 'Western Sahara', alpha_2_code: 'EH', alpha_3_code: 'ESH', numeric_code: '732', is_to_ship: true)
Nation.create(name: 'Yemen', alpha_2_code: 'YE', alpha_3_code: 'YEM', numeric_code: '887', is_to_ship: true)
Nation.create(name: 'Zambia', alpha_2_code: 'ZM', alpha_3_code: 'ZMB', numeric_code: '894', is_to_ship: true)
Nation.create(name: 'Zimbabwe', alpha_2_code: 'ZW', alpha_3_code: 'ZWE', numeric_code: '716', is_to_ship: true)
